<a href="https://colab.research.google.com/github/rayvonandeche/SemProject_MLEngine/blob/main/Accounts%20Receivable%20invoices%20(IBM%20sample%2C%20WA_Fn-UseC_)_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Project 1 Deliverable

### Team 7: Bomatrack
Members:

* 192076,Austin Maina
* 190159,Andeche Atetwe
* 190375,Yassir Mohammed
* 191258,Emmanuel Onyango

BomaTrack is a property-management application designed for landlords, for monitoring units, tenancies and rent payments. The research area is predicting payment behaviour from a tenant's previous invoice and payment history.

Outputs: **how late will this rent payment be?** , **will this ren payment be late at all?** and  **hou much should the units be priced**

### Possible Datasets
We looked at 5 datasets:
1. Accounts Receivable Invoices(IBM sample, WA_Fn-UseC_)

* Candidate output variable: DaysLate, DaysToSettle, or a late-payment yes/no indicator.

2. Nairobi Rent Listings(Kaggle "Kenya Housing" + web search)

* Candidate output variable: Price.
Good dataset due the availability of local rental market data.

3. UCI Credit Card Default(UCI 350, Yeh & Lien 2009)

* Candidate output variable: Next month default

4. Telco Customer Churn(IBM)

* Candidate output variable: Tenants Churn.

## Why we chose dataset 1(Accounts Receivable Invoices(IBM sample, WA_Fn-UseC_))
Rent payments work like invoices, so this dataset is the closest match to the rent problem. It also allows time-based testing using 2012 data for training and 2013 data for testing.

**The main limitation is that it uses business invoices, not real tenant records.**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# load the databse from url
url = 'https://raw.githubusercontent.com/pthiagu2/DataMining/master/WA_Fn-UseC_-Accounts-Receivable.csv'
df = pd.read_csv(url)
df.head(3)

,countryCode,customerID,PaperlessDate,invoiceNumber,InvoiceDate,DueDate,InvoiceAmount,Disputed,SettledDate,PaperlessBill,DaysToSettle,DaysLate
0,391,0379-NEVHP,4/6/2013,611365,1/2/2013,2/1/2013,55.94,No,1/15/2013,Paper,13,0
1,406,8976-AMJEO,3/3/2012,7900770,1/26/2013,2/25/2013,61.74,Yes,3/3/2013,Electronic,36,6
2,391,2820-XGXSB,1/26/2012,9231909,7/3/2013,8/2/2013,65.88,No,7/8/2013,Electronic,5,0

### What is the shape of the dataset?

In [ ]:
df.shape

(2466, 12)

### What are the data types

In [ ]:
print(df.dtypes)

countryCode        int64
customerID        object
PaperlessDate     object
invoiceNumber      int64
InvoiceDate       object
DueDate           object
InvoiceAmount    float64
Disputed          object
SettledDate       object
PaperlessBill     object
DaysToSettle       int64
DaysLate           int64
dtype: object

### Are there missing values?

In [ ]:
print(df.isna().sum())
# No missing value for the selected dataset

countryCode      0
customerID       0
PaperlessDate    0
invoiceNumber    0
InvoiceDate      0
DueDate          0
InvoiceAmount    0
Disputed         0
SettledDate      0
PaperlessBill    0
DaysToSettle     0
DaysLate         0
dtype: int64

In [ ]:
df_sample = pd.concat([df.head(15), df.tail(20)])
df_sample.shape
df_sample

,countryCode,customerID,PaperlessDate,invoiceNumber,InvoiceDate,DueDate,InvoiceAmount,Disputed,SettledDate,PaperlessBill,DaysToSettle,DaysLate
0,391,0379-NEVHP,4/6/2013,611365,1/2/2013,2/1/2013,55.94,No,1/15/2013,Paper,13,0
1,406,8976-AMJEO,3/3/2012,7900770,1/26/2013,2/25/2013,61.74,Yes,3/3/2013,Electronic,36,6
2,391,2820-XGXSB,1/26/2012,9231909,7/3/2013,8/2/2013,65.88,No,7/8/2013,Electronic,5,0
3,406,9322-YCTQO,4/6/2012,9888306,2/10/2013,3/12/2013,105.92,No,3/17/2013,Electronic,35,5
4,818,6627-ELFBK,11/26/2012,15752855,10/25/2012,11/24/2012,72.27,Yes,11/28/2012,Paper,34,4
5,818,5148-SYKLB,8/28/2013,18104516,1/27/2012,2/26/2012,94.00,Yes,2/22/2012,Paper,26,0
6,897,8690-EEBEO,12/5/2012,23864272,8/13/2013,9/12/2013,74.69,No,9/9/2013,Electronic,27,0
7,770,4460-ZXNDN,6/27/2013,27545037,12/16/2012,1/15/2013,75.06,No,1/12/2013,Paper,27,0
8,770,3831-FXWYK,3/8/2013,28049695,5/14/2012,6/13/2012,80.07,Yes,7/1/2012,Paper,48,18
9,897,7654-DOLHO,4/4/2012,32277701,7/1/2013,7/31/2013,48.33,No,7/26/2013,Electronic,25,0
10,770,3993-QUNVJ,12/31/2012,35868002,3/31/2012,4/30/2012,75.33,No,4/16/2012,Paper,16,0
11,406,5284-DJOZO,9/11/2012,36478577,8/7/2013,9/6/2013,73.35,No,8/15/2013,Electronic,8,0
12,818,5924-UOPGH,6/6/2013,36620839,5/8/2013,6/7/2013,90.08,Yes,6/9/2013,Paper,32,2
13,406,9117-LYRCE,7/5/2013,41324194,10/21/2012,11/20/2012,57.17,No,11/30/2012,Paper,40,10
14,818,7695-NKUXM,11/21/2012,42511106,11/7/2012,12/7/2012,50.02,No,11/18/2012,Paper,11,0
2446,770,7856-ODQFO,8/5/2012,9912278044,11/4/2013,12/4/2013,21.73,No,11/19/2013,Electronic,15,0
2447,770,3831-FXWYK,3/8/2013,9914585915,12/1/2013,12/31/2013,86.29,No,1/4/2014,Electronic,34,4
2448,391,0709-LZRJV,6/20/2013,9922568654,9/3/2012,10/3/2012,42.67,No,10/9/2012,Paper,36,6
2449,406,9725-EZTEJ,3/17/2012,9923030049,12/26/2012,1/25/2013,71.12,Yes,1/29/2013,Electronic,34,4
2450,818,5148-SYKLB,8/28/2013,9923599437,10/4/2013,11/3/2013,76.18,No,10/27/2013,Electronic,23,0
2451,391,5529-TBPGK,8/9/2013,9923678452,6/4/2013,7/4/2013,68.40,No,7/7/2013,Paper,33,3
2452,406,4640-FGEJI,4/4/2013,9934734648,4/24/2012,5/24/2012,74.19,No,5/22/2012,Paper,28,0
2453,391,9212-BTDMX,4/22/2012,9936482887,7/27/2013,8/26/2013,68.07,No,8/8/2013,Electronic,12,0
2454,391,9014-WENVB,8/3/2013,9938539742,11/26/2012,12/26/2012,65.19,No,12/25/2012,Paper,29,0
2455,897,3676-CQAIF,7/29/2013,9938923133,1/15/2012,2/14/2012,48.06,No,2/22/2012,Paper,38,8
2456,818,8102-ABPKQ,8/29/2013,9941572096,11/18/2012,12/18/2012,74.16,Yes,1/2/2013,Paper,45,15
2457,818,5924-UOPGH,6/6/2013,9947321662,9/8/2012,10/8/2012,93.09,Yes,10/15/2012,Paper,37,7
2458,391,5529-TBPGK,8/9/2013,9968504859,6/10/2013,7/10/2013,38.95,No,7/5/2013,Paper,25,0
2459,770,9323-NDIOV,7/9/2012,9976671102,3/31/2012,4/30/2012,28.30,No,4/28/2012,Paper,28,0
2460,818,5148-SYKLB,8/28/2013,9982124268,9/21/2012,10/21/2012,59.00,Yes,10/28/2012,Paper,37,7
2461,391,6708-DPYTF,8/2/2012,9982796720,10/18/2013,11/17/2013,79.61,No,12/1/2013,Electronic,44,14
2462,391,9841-XLGBV,1/3/2013,9983237240,9/19/2012,10/19/2012,38.25,No,10/13/2012,Paper,24,0
2463,770,7856-ODQFO,8/5/2012,9986249860,7/2/2012,8/1/2012,67.59,No,7/27/2012,Paper,25,0
2464,770,7050-KQLDO,9/29/2012,9989225541,4/27/2012,5/27/2012,53.16,No,5/18/2012,Paper,21,0
2465,406,9758-AIEIK,4/23/2012,9990243864,7/4/2013,8/3/2013,68.66,No,7/18/2013,Electronic,14,0